(function(){
  sy=window.sy||{};
  sy.dataSet=function(){
	this.title="";
    this.descript="";
    this.questions=[];
  }
  sy.question=function(){
	this.descript="";
	this.options=[];
  }
  sy.qOption=function(){
	this.type=0;
	this.descript="";
  }
  sy.createQoption=function(){
	return new sy.qOption();
  }
  sy.createQ=function(){
	return new sy.question();
  }
  sy.createData=function(){
	return new sy.dataSet();
  }
  sy.dataSetFlash=function(){
	DataSet={};
	DataSet=sy.createData();
  }
  sy.dataSetFlash();
  sy.publish=function(){
    var i,_qu,_opt,j;
    for(i=0;i<Blocks.length;i++){
      if(Blocks[i].getIsTitle()){
        DataSet.title=Blocks[i].getTitle();
      }
      else{
    	if(Blocks[i].getIsDescript()){
          DataSet.descript=Blocks[i].getTitle();
    	}
    	else{
          _qu=sy.createQ();
          _qu.descript=Blocks[i].getTitle();
          for(j=0;j<Blocks[i].getOptionLen();j++){
        	_opt=sy.createQoption();
        	tmpOpt=sy.getOption(Blocks[i],j);
        	_opt.type=tmpOpt.getType();
        	_opt.descript=tmpOpt.getDescript();
        	_qu.options.push(_opt);
          }
          DataSet.questions.push(_qu);
    	}
      }
    }
    $.ajax({
      type:"post",
      url:"http://127.0.0.1:8081/surveyOI/_core/server.php?query=survey",
      data:{dataSet:DataSet},
      success:function(data){
    	alert(data);
      }
    });
  }
})()