(function(){
  sy=window.sy||{};
  sy.dataSet=function(){
	this.title="";
    this.descript="";
    this.questions=[];
  }
  sy.question=function(){
	this.descript="";
	this.options=[];
  }
  sy.qOption=function(){
	this.type=0;
	this.descript="";
  }
  sy.createQoption=function(){
	return new sy.qOption();
  }
  sy.createQ=function(){
	return new sy.question();
  }
  sy.createData=function(){
	return new sy.dataSet();
  }
  sy.dataSetFlash=function(){
	DataSet={};
	DataSet=sy.createData();
  }
  sy.dataSetFlash();
  sy.publish=function(_isPublish){
    var i,_qu,_opt,j;
    for(i=0;i<Blocks.length;i++){
      if(0==i){
        DataSet.title=Blocks[i].getTitle();
      }
      if(i==1){
    	DataSet.descript=Blocks[i].getDescript();
    	continue;
      }
      if(i==2){
        DataSet.subject=Blocks[i].getSubject();
      }
      if(i>2){
        _qu=sy.createQ();
        _qu.descript=Blocks[i].getTitle();
        for(j=0;j<Blocks[i].getOptionLen();j++){
          _opt=sy.createQoption();
          tmpOpt=sy.getOption(Blocks[i],j);
          _opt.type=tmpOpt.getType();
          _opt.descript=tmpOpt.getDescript();
          _qu.options.push(_opt);
        }
        DataSet.questions.push(_qu);
      }
    }
    $.ajax({
      type:"post",
      url:"http://127.0.0.1:8081/surveyOI/_core/server.php?query=survey"+(_isPublish===0?"&save=1":""),
      data:{dataSet:DataSet},
      success:function(data){
    	//alert(data);
        var pos;
        pos=data.indexOf("save");
        if(pos!=-1){
          alert("±£´æ³É¹¦,Ð»Ð»£¡");
          return;
        }
    	if(data.length>30) return;
        window.location="http://127.0.0.1:8081/surveyOI/doc/QuestionnaireLink.php"+"?"+"url="+data.substr(4,data.length-3);
      }
    });
  }
})()